version: '2'
services:
  kibana:
    image: jecklgamis/kibana:latest
    ports:
      - "5601:5601"
    links:
      - "elasticsearch:es.local"
  elasticsearch:
    image: jecklgamis/elasticsearch:latest
    expose:
      - "9200"
      - "9300"
  beats:
    image: jecklgamis/beats:latest
    links:
      - "elasticsearch:es.local"
      - "kibana:kibana.local"
