all:
	cat ./Makefile
image:
	docker build -t jecklgamis/oracle-java-runtime:latest .
run:
	docker run jecklgamis/oracle-java-runtime
run-bash:
	docker run -i -t jecklgamis/oracle-java-runtime:latest /bin/bash
